### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by LucVosatkova** [bratislava/bratislava.sk#1048]
Chceme upravit footer tak, aby boli pri kontaktoch fieldy upravitelne v strapi (napr kontakt pre media je momentalne hardcoded) a pri všeobecnom kontakte "nazov" chyba. 

![Image](https://github.com/bratislava/bratislava.sk/assets/126063072/0ee6f35c-4d63-4623-8efa-bed13aa258da)

1. Kontakt pre media (nazov fieldu pridat do strapi) 
2. Pridat do strapi a footeru "Všeobecný kontakt"
3. Ku infolinke/tel.c. pridat "Infolinka 8:30-14:00"

**Comment by radoslavzeman** [comment]
Vytvoril by som v Strapi komponent v Blocks, ktory bude obsahovat fieldy: label*, phone, email. A vo Footer by som ich pridal ako repeatable component, namiesto aktualnych troch hardcoded fieldov.
