### ISSUE TITLE
Missing RSS

### ISSUE THREAD

**Issue by idigest** [bratislava/bratislava.sk#317]
In past it was possible to read website news grace  to rss feeds...

**Comment by mpinter** [comment]
Thank you for your feedback - we can't promise this right away but will definitely look into it.

**Comment by mpinter** [comment]
Alright, seeing the end of Q2 is nearing and there was still no opportunity to touch this, we apologise for an incorrect estimate. The focus of the team is presently on other projects, and our capacity for homepage is taken by maintenance and fixing of various UX/content/accessibility issues, the RSS feed being lower on the list priorities.

Will always be happy to help with and pull requests submitted for this though.
