### ISSUE TITLE
Missing webcams

### ISSUE THREAD

**Issue by idigest** [bratislava/bratislava.sk#376]
Hello, this is not a programming issue - but old webcams and the site kamery.bratislava.sk are missing beginning Nov. 8 :-(

**Comment by mpinter** [comment]
Hi - this service isn't really managed by us therefore the lack of info (on our side as well). It's also quite possible it will be turned off in the future. But rechecking it now after a bit: it seems it runs for now, the page redirects to http://ba-cam-canex.sk/, not all of the cams are online but some still work.

**Comment by idigest** [comment]
Thanks.

Vlado Bibel - Panorama.sk
<http://www.panorama.sk/en/slovakia/webcams>
<http://www.panorama.sk>https:// <http://www.panorama.sk/en/slovakia>
www.panorama.sk
E-mail: ***@***.***
Tel.: 00 421 905 454 205

Webkamery Slovensko a okolie:
<http://www.panorama.sk/sk/online-kamery>https://
<http://www.panorama.sk/en/slovakia>www.panorama.sk/sk/online-kamery
