### ISSUE TITLE
Mapa rozkopavok - release 1.6.

### ISSUE THREAD

**Issue by LucVosatkova** [bratislava/bratislava.sk#637]
Na HP v zalozke "rozkopávky" chceme, aby namiesto articles list componentu bola vlozena mapa https://cdn-api.bratislava.sk/static-pages/closures-and-restrictions-map/index.html?lang=sk

**Comment by LucVosatkova** [comment]
Nasadit na DEV a na zivu dat az 15.3. (pripadne este xcheck s Kubom)

**Comment by LucVosatkova** [comment]
/doprava-a-mapy/sprava-a-udrzba-komunikacii/rozkopavky-a-uzavery vymenim articels list za iframe s mapou v strapi ja, task sa tyka len HP

**Comment by Balros** [comment]
Nasledne v kode je potrebne odstranit kod na 2 miestach:

- Homepage `Posts` kde ziju teraz 2 riesenia naraz ktore sa po deadline vymenia a nasledne tam zostane zastarany nepouzivany kod
- `doprava-a-mapy/sprava-a-udrzba-komunikacii/rozkopavky-a-uzavery` pouziva Articles List - Zoznam uzavierok ktory po nahradeni @LucVosatkova  bude mozne tiez z kodu odstranit, nakolko nikde inde sa to nepouziva.

**Comment by Balros** [comment]
testovatelne na adrese [bratislava-development](https://bratislava-next.dev.bratislava.sk/) kedze to je nase testovacie prostredie tak to tam v case testovania byt nemusi, nahodim to tam vtedy znovu

**Comment by LucVosatkova** [comment]
@Balros Adam pls po checku s Kubom, mala zmena: btn by mal mat text "Viac informacii" a smerovat by mal na doprava-a-mapy/sprava-a-udrzba-komunikacii

**Comment by LucVosatkova** [comment]
@Balros este mi napadlo, ze toto si ako myslel? doprava-a-mapy/sprava-a-udrzba-komunikacii/rozkopavky-a-uzavery pouziva Articles List - Zoznam uzavierok ktory po nahradeni @LucVosatkova bude mozne tiez z kodu odstranit, nakolko nikde inde sa to nepouziva. - **Articels list sa pouziva na inych pages** a je to normalne komponent v strapi

**Comment by Balros** [comment]
Developersky task, pridal som formatovanie do textu vid. https://github.com/bratislava/bratislava.sk/issues/637#issuecomment-1457918917 Tento `Articles List - Zoznam uzavierok` je z development pohladu nieco ine ako `Articles list`

**Comment by Balros** [comment]
Zmena datumu publikovania z 15. marec, na neurcito (TBD 17. marec).

**Comment by KuboHBA** [comment]
v iframe nefunguje zobrazenie mapy na celu obrazovku, ikonka reaguje na kliknutie, nic ale neurobi @Balros

**Comment by KuboHBA** [comment]
aj lokalizacia mi nefunguje, treba to asi vsetko povolit v iframe

**Comment by radoslavzeman** [comment]
Presunute na 1.6.
