### ISSUE TITLE
Banner 1 DDL.1.4.

### ISSUE THREAD

**Issue by LucVosatkova** [bratislava/bratislava.sk#658]
https://www.figma.com/file/17wbd0MDQcMW9NbXl6UPs8/DS-ESBS%3A-Component-library?node-id=5484%3A6779&t=b33CpxjKpXwoxR9E-4

Mobil: https://www.figma.com/file/SFbuULqG1ysocghIga9BZT/ESBS---ready-for-dev-(Mestsk%C3%A9-konto%2C-Ma%C5%A5a)?node-id=2421%3A8109&t=XZ7OwfJcmDBwuUVO-4 

- pridat novu sekciu do Strapi

Cheme v Strapi vediet upravit: 
- obrazok
- vybrat rozlozenie (left/right)
- headline
- text _(volitelne)_
- primary btn (+ pridat page/url kam ma smerovat) _(volitelne)_
- secondary btn (+ pridat page/url kam ma smerovat) _(volitelne)_

Farba banneru je urcena podla farby kategorie stranky

**Comment by radoslavzeman** [comment]
Mame k tomu aj mobilny dizajn?
