### ISSUE TITLE
Benefit component (Icon title desc) DDL 1.4.

### ISSUE THREAD

**Issue by LucVosatkova** [bratislava/bratislava.sk#721]
https://www.figma.com/file/17wbd0MDQcMW9NbXl6UPs8/DS-ESBS%3A-Component-library?node-id=5865-16442&t=ieCEpuieDa65uGB6-4

V strapi chceme editovat: 
- Headline sekcie
- Subtext sekcie (optional)
- pocet stlpcov (3 alebo 4)

Pre kazdy stlpec:
- Nahrat ikonu svg/png (pozadie v kode nastavene podla farby kategorie)
- Headline
- subtext (optional)
- BTN (optional)
   - text
   - link interny/externy

**Comment by radoslavzeman** [comment]
Chyba dorobit:
- button link
- nastavovanie postu stlpcov
