### ISSUE TITLE
Firefox - nefunguje odkaz na bratislavske konto

### ISSUE THREAD

**Issue by Braddock-sk** [bratislava/bratislava.sk#872]
![bratislava](https://user-images.githubusercontent.com/69510315/231451499-41e2fc28-060c-470c-832e-704558275860.PNG)

Pouzivam najnovsiu verziu Firefoxu 112.0

Este som si vsimol ze stranka o ochrane osobnych udajov nema obshah
https://bratislava.sk/ochrana-osobnych-udajov

**Comment by radoslavzeman** [comment]
Vďaka za upozornenie, oba problémy by mali byť už odstránené.
