### ISSUE TITLE
Rozkopavky - slug change & tab HP

### ISSUE THREAD

**Issue by LucVosatkova** [bratislava/bratislava.sk#968]
stranku https://bratislava.sk/doprava-a-mapy/sprava-a-udrzba-komunikacii/rozkopavky-a-uzavery je potrebne premenovat na Obmedzenia a poruchy, teda slug by mal byt https://bratislava.sk/doprava-a-mapy/sprava-a-udrzba-komunikacii/obmedzenia-a-poruchy 

**HP**
Tab zmenit na  “Obmedzenia” v EN na “Restrictions”

**Comment by MarekBodingerBA** [comment]
@LucVosatkova 
Všetko toto sa dá cez Strapi. 

https://bratislava-strapi.bratislava.sk/admin/content-manager/singleType/api::homepage.homepage?plugins[i18n][locale]=sk

![Image](https://github.com/bratislava/bratislava.sk/assets/104828482/ba20592c-c767-481a-9ef9-4e790391e9d2)
